from enum import Enum
class DeviceType(Enum):
    Camera = 0
    Lamp = 1
    Socket = 2
    Thermostat = 3
    Printer = 4
    Sensor = 5
    light_switch = 6
    Counter = 7
    Lock = 8
    Skip = 9
vendor_type = {"Arlo": DeviceType.Camera, "Ring": DeviceType.Camera, "Nes": DeviceType.Camera,
               "Wyze": DeviceType.Camera, "EZVIZ": DeviceType.Camera,
               "Reolink": DeviceType.Camera, "Blink": DeviceType.Camera, "Logitech": DeviceType.Camera,
               "D-Link": DeviceType.Camera, "TP-Link": DeviceType.Camera,
               "Lorex": DeviceType.Camera, "Amcrest": DeviceType.Camera, "Axis Communications": DeviceType.Camera,
               "Bosch": DeviceType.Camera, "Ростелеком": DeviceType.Camera,
               "SberDevices": DeviceType.Camera, "Ivideon": DeviceType.Camera, "VMS": DeviceType.Camera,
               "iPera": DeviceType.Camera, "Novicam": DeviceType.Camera,
               "Verkada": DeviceType.Camera, "Hikvision": DeviceType.Camera, "Cootli": DeviceType.Camera,
               "Foscam": DeviceType.Camera, "Trendnet": DeviceType.Camera,
               "Vivotek": DeviceType.Camera, "Panasonic": DeviceType.Camera, "Samsung": DeviceType.Camera,
               "Dahua": DeviceType.Camera, "Netgear": DeviceType.Camera,
               "Linksys": DeviceType.Camera, "Swann": DeviceType.Camera, "Owl": DeviceType.Camera,
               "LaView": DeviceType.Camera, "Tenvis": DeviceType.Camera,
               "Wanscam": DeviceType.Camera, "Xiaomi": DeviceType.Camera, "Annke": DeviceType.Camera,
               "Zmodo": DeviceType.Camera,
               "Philips": DeviceType.Lamp, "LIFX": DeviceType.Lamp, "TP-Link Kasa": DeviceType.Lamp,
               "Yeelight": DeviceType.Lamp, "LED": DeviceType.Lamp, "RokettoMi": DeviceType.Lamp,
               "Sengled": DeviceType.Lamp,
               "Wiz": DeviceType.Lamp, "IKEA Tradfri": DeviceType.Lamp, "Nanoleaf": DeviceType.Lamp,
               "Cree Lighting": DeviceType.Lamp, "GE Lighting": DeviceType.Lamp,
               "Osram Ledvance": DeviceType.Lamp, "Elgato": DeviceType.Lamp, "SberDevices": DeviceType.Lamp,
               "Rubetek": DeviceType.Lamp, "Redmond": DeviceType.Lamp,
               "Gauss": DeviceType.Lamp, "EKF": DeviceType.Lamp, "Navigator": DeviceType.Lamp,
               "Feron": DeviceType.Lamp, "Jazzway": DeviceType.Lamp,
               "Camelion": DeviceType.Lamp, "Era": DeviceType.Lamp, "ASD": DeviceType.Lamp, "Uniel": DeviceType.Lamp,
               "SmartBuy": DeviceType.Lamp,
               "HP": DeviceType.Printer, "Epson": DeviceType.Printer, "Canon": DeviceType.Printer,
               "Brother": DeviceType.Printer, "Xerox": DeviceType.Printer,
               "Samsung": DeviceType.Printer, "Lexmark": DeviceType.Printer, "Kyocera": DeviceType.Printer,
               "OKI": DeviceType.Printer, "Ricoh": DeviceType.Printer,
               "Konica": DeviceType.Printer, "Dell": DeviceType.Printer, "Lenovo": DeviceType.Printer,
               "Pantum": DeviceType.Printer, "Olivetti": DeviceType.Printer,
               "Sharp": DeviceType.Printer, "Muratec": DeviceType.Printer, "Riso": DeviceType.Printer,
               "Bosch": DeviceType.Sensor, "Sensirion": DeviceType.Sensor, "Xiaomi": DeviceType.Sensor,
               "Samsung": DeviceType.Sensor, "Fibaro": DeviceType.Sensor,
               "Sonoff": DeviceType.Sensor, "Aeotec": DeviceType.Sensor, "Zooz": DeviceType.Sensor,
               "Inovelli": DeviceType.Sensor, "Homeseer": DeviceType.Sensor,
               "Konke": DeviceType.Sensor, "Tuya": DeviceType.Sensor, "eWeLink": DeviceType.Sensor,
               "YoLink": DeviceType.Sensor, "Third Reality": DeviceType.Sensor,
               "Phillips": DeviceType.Sensor, "Infineon": DeviceType.Sensor, "STMicroelectronics": DeviceType.Sensor,
               "Texas Instruments": DeviceType.Sensor, "Murata Manufacturing": DeviceType.Sensor,
               "Honeywell": DeviceType.Sensor, "Omron": DeviceType.Sensor, "Schneider Electric": DeviceType.Sensor,
               "Siemens": DeviceType.Sensor, "ABB": DeviceType.Sensor,
               "Itron": DeviceType.Counter, "Landis": DeviceType.Counter, "Elster": DeviceType.Counter,
               "Kamstrup": DeviceType.Counter, "ADD": DeviceType.Counter,
               "Sensus": DeviceType.Counter, "Badger": DeviceType.Counter, "Neptune": DeviceType.Counter,
               "Aclara": DeviceType.Counter, "Wasion": DeviceType.Counter,
               "Linyang": DeviceType.Counter, "HND": DeviceType.Counter, "Holley": DeviceType.Counter,
               "Sanxing": DeviceType.Counter, "Clou": DeviceType.Counter,
               "NARI": DeviceType.Counter, "Hexing": DeviceType.Counter, "Apator": DeviceType.Counter,
               "Diehl": DeviceType.Counter, "Sagemcom": DeviceType.Counter,
               "Iskraemeco": DeviceType.Counter, "NKT": DeviceType.Counter, "ZIV": DeviceType.Counter,
               "EDMI": DeviceType.Counter, "Secure Meters": DeviceType.Counter,
               "TP-Link": DeviceType.light_switch, "WeMo": DeviceType.light_switch, "Lutron": DeviceType.light_switch,
               "Insteon": DeviceType.light_switch, "iRidium": DeviceType.light_switch,
               "Leviton": DeviceType.light_switch, "Treatlife": DeviceType.light_switch,
               "Gosund": DeviceType.light_switch, "Merkury Innovations": DeviceType.light_switch,
               "Inovelli": DeviceType.light_switch,
               "Zooz": DeviceType.light_switch, "GE CYNC": DeviceType.light_switch, "Legrand": DeviceType.light_switch,
               "Schneider Electric": DeviceType.light_switch, "Enerwave": DeviceType.light_switch,
               "Aeotec": DeviceType.light_switch, "Phillips": DeviceType.light_switch,
               "Honeywell": DeviceType.light_switch, "Orvibo": DeviceType.light_switch, "Tuya": DeviceType.light_switch,
               "Smart Life": DeviceType.light_switch, "Yagusmart": DeviceType.light_switch,
               "Lonsonho": DeviceType.light_switch, "MoesHouse": DeviceType.light_switch,
               "LoraTap": DeviceType.light_switch,
               "August": DeviceType.Lock, "Yale": DeviceType.Lock, "Schlage": DeviceType.Lock,
               "Kwikset": DeviceType.Lock, "Tantos": DeviceType.Lock,
               "Level Home": DeviceType.Lock, "Lockly": DeviceType.Lock, "Nuki": DeviceType.Lock,
               "Danalock": DeviceType.Lock, "Netatmo": DeviceType.Lock,
               "Bosch": DeviceType.Lock, "eufy": DeviceType.Lock, "Wyze": DeviceType.Lock, "Ultraloq": DeviceType.Lock,
               "Arlo": DeviceType.Lock,
               "Igloohome": DeviceType.Lock, "Schlage": DeviceType.Lock, "Yale": DeviceType.Lock,
               "Kwikset": DeviceType.Lock, "Nest": DeviceType.Lock,
               "SimpliSafe": DeviceType.Lock, "Ring": DeviceType.Lock, "Abode": DeviceType.Lock,
               "ecobee": DeviceType.Lock, "Codelocks": DeviceType.Lock,
               "TP-Link": DeviceType.Socket, "WeMo": DeviceType.Socket, "Samsung": DeviceType.Socket,
               "Sonoff": DeviceType.Socket, "Meross": DeviceType.Socket,
               "Teckin": DeviceType.Socket, "VOCOlinc": DeviceType.Socket, "iDevices": DeviceType.Socket,
               "ConnectSense": DeviceType.Socket, "Kasa": DeviceType.Socket,
               "Etekcity": DeviceType.Socket, "Gosund": DeviceType.Socket, "Treatlife": DeviceType.Socket,
               "Energenie": DeviceType.Socket, "TP-Link": DeviceType.Socket,
               "Philips": DeviceType.Socket, "IKEA": DeviceType.Socket, "Samsung": DeviceType.Socket,
               "Amazon": DeviceType.Socket, "Nest": DeviceType.Socket,
               "Wemo": DeviceType.Socket, "Leviton": DeviceType.Socket, "myStrom": DeviceType.Socket,
               "Nest": DeviceType.Thermostat, "Honeywell": DeviceType.Thermostat, "ecobee": DeviceType.Thermostat,
               "Sensi": DeviceType.Thermostat, "Teplocom": DeviceType.Thermostat,
               "Carrier": DeviceType.Thermostat, "Trane": DeviceType.Thermostat, "Johnson": DeviceType.Thermostat,
               "Resideo": DeviceType.Thermostat, "Emerson": DeviceType.Thermostat,
               "Mysa": DeviceType.Thermostat, "Flair": DeviceType.Thermostat, "tado": DeviceType.Thermostat,
               "Netatmo": DeviceType.Thermostat, "Venstar": DeviceType.Thermostat,
               "Lux": DeviceType.Thermostat, "Robertshaw": DeviceType.Thermostat,
               "White-Rodgers": DeviceType.Thermostat, "Braeburn": DeviceType.Thermostat, "Vine": DeviceType.Thermostat,
               "Zen": DeviceType.Thermostat, "Salus": DeviceType.Thermostat, "Danfoss": DeviceType.Thermostat,
               "Uponor": DeviceType.Thermostat
               }
